language: ruby
rvm:
- 2.0.0
script:
- bundle install
- bundle exec rake
env:
  global:
  - secure: gSuA/tJn7gyL4vg87NXLctNaI9bEisbmrqgZWseaAStxfQ7ksYqi0SmRyq0D5YNiz5IAxBWDIkb67LZH9oj0SIpcoUwmxr6anbGoXyVuSGF54Gwh45KQj/FkO3WbhaVaKd0rjcofq58xOKMOXAQGP4NQtF92BEH46i4iRXPu/HM=
  - secure: lW1n1kNsbZ6YErxtLH+xrFEuLT5+Brnv4cFanZ3V3BT6EOgVZ/Ceh2hAww30Wxo1EDfkz0y3hBPo5+9S4O4wneKDDDRM0YGzCXt1Qo6IwjkjI3QE8BYIXyT6enFRTLZd1/+QGeEO6szUwP4+rHrbvKO0w0gitWvynRy4Jl4yg80=
  - TEST_ELB=roadworker-1619064454.ap-northeast-1.elb.amazonaws.com.
  - TEST_CF=dwq5bksfxh5xn.cloudfront.net.
  - TEST_DELAY=0.3
