language: ruby
cache: bundler
sudo: false
rvm:
- 2.0.0
script:
- bundle exec rake
env:
  global:
  - TEST_AWS_ACCESS_KEY_ID=AKIAIGY3QFZA5LBYEDJA
  - TEST_AWS_SECRET_ACCESS_KEY=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
  - TEST_ELB=roadworker-1619064454.ap-northeast-1.elb.amazonaws.com.
  - TEST_CF=dwq5bksfxh5xn.cloudfront.net.
  - TEST_DELAY=0.3
  - TEST_VPC_REGION=ap-northeast-1
  - TEST_VPC1=vpc-18f5097d
  - TEST_VPC2=vpc-e5f50980
  - TEST_INTERVAL=3
  - AWS_REGION=ap-northeast-1
addons:
  apt:
    packages:
      - libpcap-dev
