# Site settings
title: Roadworker
email: sgwr_dts@yahoo.co.jp
description: "Roadworker is a tool to manage Route53. It defines the state of Route53 using DSL, and updates Route53 according to DSL."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://roadworker.codenize.tools/"
github_url: "https://github.com/winebarrel/roadworker"
twitter_username: sgwr_dts
github_username:  winebarrel
original_background_image_url: "https://www.flickr.com/photos/dharder9475/15519938961/in/photolist-64ZiGH-dAMcPo-9iWxBp-5qNPn6-pDrK9v-ctkB1U-7efzX6-nDckb7-orpaWw-aUrvcV-3ZLhG-73eoxr-5qNNX4-hGViQu-5qNP26-fSDNgM-azww16-q8Kf1n-fyh93n-jnkJt4-4tvMib-4T8adQ-jspWN-oLZZvA-A6hNH-fywqxq-bC1ap8-kmdxAx-gudUPj-sfirN-62Lebe-dF7wkC-6vaQp1-qjaoSM-6zP42s-eTLAkU-LWKhs-bp6eRm-5qNNBt-f3ASCY-4KGjy6-cZ4pnj-eUVy2u-bMGXD6-jsRjqV-3bJPfM-cx4JQ9-eGK644-aLcvgx-8VqoQE"
background_image_licence: "images/background.license"

# Build settings
markdown: kramdown
