# Site settings
title: Roadworker
email: sgwr_dts@yahoo.co.jp
description: "Roadworker is a tool to manage Route53. It defines the state of Route53 using DSL, and updates Route53 according to DSL."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://roadworker.codenize.tools/"
twitter_username: sgwr_dts
github_username:  winebarrel

# Build settings
markdown: kramdown
